name: deploy cgxb.deno.dev

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - run: pnpm install

      - run: pnpm run build

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: cgxb
          entrypoint: https://deno.land/std@0.189.0/http/file_server.ts
          root: docs/.vitepress/dist
